package controllers

import (
	"bytes"
	"fmt"
	"time"

	"ganium/src/models"

	"github.com/jung-kurt/gofpdf"
)

func buildScanPDF(userEmail string, record *models.ScanRecord) ([]byte, error) {
	pdf := newReportPDF("Ganium Scan Report", "Scan result generated by Ganium")
	addMetaLine(pdf, "User", userEmail)
	addMetaLine(pdf, "Content Type", record.ContentType)
	addMetaLine(pdf, "Classification", record.Classification)
	addMetaLine(pdf, "Risk Score", record.RiskScore)
	addMetaLine(pdf, "Tokens Used", fmt.Sprintf("%d", record.TokensUsed))
	addMetaLine(pdf, "Created At", record.CreatedAt.Format(time.RFC3339))
	addSection(pdf, "Content", record.Content)
	addSection(pdf, "Explanation", record.Explanation)
	addSection(pdf, "Recommendations", record.Recommendations)
	return pdfBytes(pdf)
}

func buildReceiptPDF(userEmail string, receipt models.ReceiptData) ([]byte, error) {
	pdf := newReportPDF("Ganium Payment Receipt", "Payment confirmation receipt")
	addMetaLine(pdf, "Customer", receipt.PayerName)
	addMetaLine(pdf, "Email", receipt.PayerEmail)
	addMetaLine(pdf, "Reference", receipt.Reference)
	addMetaLine(pdf, "Amount", fmt.Sprintf("%s %.2f", receipt.Currency, receipt.Amount))
	addMetaLine(pdf, "Status", receipt.Status)
	addMetaLine(pdf, "Method", receipt.PaymentMethod)
	addMetaLine(pdf, "Date", receipt.TransactionDate.Format(time.RFC3339))
	addMetaLine(pdf, "Generated For", userEmail)
	addSection(pdf, "Description", receipt.Description)
	return pdfBytes(pdf)
}

func newReportPDF(title, subtitle string) *gofpdf.Fpdf {
	pdf := gofpdf.New("P", "mm", "A4", "")
	pdf.SetMargins(16, 16, 16)
	pdf.SetAutoPageBreak(true, 16)
	pdf.AddPage()
	pdf.SetFont("Helvetica", "B", 20)
	pdf.CellFormat(0, 12, title, "", 1, "L", false, 0, "")
	pdf.SetFont("Helvetica", "", 11)
	pdf.SetTextColor(80, 80, 80)
	pdf.MultiCell(0, 6, subtitle, "", "L", false)
	pdf.Ln(4)
	pdf.SetTextColor(0, 0, 0)
	return pdf
}

func addMetaLine(pdf *gofpdf.Fpdf, label, value string) {
	pdf.SetFont("Helvetica", "B", 11)
	pdf.CellFormat(45, 7, label+":", "", 0, "L", false, 0, "")
	pdf.SetFont("Helvetica", "", 11)
	pdf.MultiCell(0, 7, value, "", "L", false)
}

func addSection(pdf *gofpdf.Fpdf, heading, body string) {
	if body == "" {
		return
	}
	pdf.Ln(2)
	pdf.SetFont("Helvetica", "B", 12)
	pdf.CellFormat(0, 8, heading, "", 1, "L", false, 0, "")
	pdf.SetFont("Helvetica", "", 11)
	pdf.MultiCell(0, 6, body, "", "L", false)
	pdf.Ln(2)
}

func pdfBytes(pdf *gofpdf.Fpdf) ([]byte, error) {
	var buf bytes.Buffer
	if err := pdf.Output(&buf); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}
